spring.application.name=muttleytrab
spring.datasource.url=jdbc:mysql://localhost:3306/muttley?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.mvc.hiddenmethod.filter.enabled=true
spring.thymeleaf.cache=false
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=muttley.fateczl@gmail.com
spring.mail.password=ycnk wnmo hbgi mflq

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

linkedin.client.id=77my412yudznpp
linkedin.client.secret=${LINKEDIN_CLIENT_SECRET}
linkedin.redirect.uri=http://127.0.0.1:8080/linkedin/callback